services:
  docker_postgres:
    container_name: docker_postgres
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./data/postgrocker:/var/lib/postgresql/data
    environment:
      TZ: UTC  # Устанавливаем временную зону на UTC
      POSTGRES_LOG_ROTATION_SIZE: 100MB  # Устанавливаем максимальный размер файла журнала в байтах
    restart: always  # Перезапускать контейнер в случае сбоя
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"  # Проброс порта 5435 для доступа извне, внутренний порт 5432
    networks:
      - postgrocker_network  # Указываем сеть, к которой будет подключен сервис



volumes:
  postgrocker:

networks:
  postgrocker_network:  # Определяем сеть
    external: true
